POST http://localhost:3003/payment/register
Content-Type: application/json

{
    "clientId": "pnVLNKXOcuoltzNzKKbk3Qe8nwIkHt5",
    "buyer_name": "Manuela D'Vila",
    "buyer_email": "manuela@pt.com",
    "buyer_CPF": "347.768.986-08",
    "amount":2000,
    "type" :"boleto"
}