POST http://localhost:3003/payment/register
Content-Type: application/json

{
    "clientId": "1XT3ywI5kMwJOlkOAgsZTVxbfBOvPHy",
    "buyer_name": "Onze",
    "buyer_email": "onze@stranger.com",
    "buyer_CPF": "427.542.490-52",
    "amount":220,
    "type" :"boleto"
}